use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use chrono::{DateTime, Utc};
// FromRow 제거: PostgreSQL BIGINT는 signed이므로 수동으로 변환 필요 

// Jupiter Swap API 요청 모델
#[derive(Debug, Serialize, Deserialize, ToSchema)]
#[schema(as = SwapTransactionRequest)]
pub struct SwapTransactionRequest {
    /// Input token mint address (e.g., USDC)
    /// 입력 토큰 주소
    #[schema(example = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v")]
    pub input_mint: String,

    /// Output token mint address (e.g., SOL)
    /// 출력 토큰 주소
    #[schema(example = "So11111111111111111111111111111111111111112")]
    pub output_mint: String,

    /// Amount to swap (in lamports/minimal units)
    /// 스왑할 수량
    #[schema(example = 1000000)]
    pub amount: u64,

    /// User public key (will sign the transaction)
    /// 사용자 공개 키 (트랜잭션 서명자)
    #[schema(example = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU")]
    pub user_public_key: String,

    /// Slippage in basis points (optional, default: 50 = 0.5%)
    /// 슬리피지 (기본점 단위, 선택사항, 기본값: 50 = 0.5%)
    #[schema(example = 50)]
    pub slippage_bps: Option<i32>,

    /// Wrap and unwrap SOL (optional, default: true)
    /// SOL 래핑/언래핑 여부 (선택사항, 기본값: true)
    pub wrap_and_unwrap_sol: Option<bool>,
}

// Jupiter Swap API 응답 모델
#[derive(Debug, Serialize, Deserialize, ToSchema)]
#[schema(as = SwapTransactionResponse)]
pub struct SwapTransactionResponse {
    /// Transaction ID (BIGSERIAL, auto-generated by DB)
    /// 트랜잭션 ID (DB에서 자동 생성, 음수 불가능)
    pub id: Option<u64>,

    /// Base58 encoded transaction bytes
    /// Base58 인코딩된 트랜잭션 바이트
    #[serde(rename = "swapTransaction")]
    pub swap_transaction: String,

    /// Last valid block height
    /// 마지막 유효 블록 높이
    #[serde(rename = "lastValidBlockHeight")]
    pub last_valid_block_height: Option<u64>,

    /// Prioritization fee in lamports (optional)
    /// 우선순위 수수료 (lamports 단위, 선택사항)
    #[serde(rename = "prioritizationFeeLamports")]
    pub prioritization_fee_lamports: Option<u64>,
}

// DB 저장용 Transaction 모델
// Note: FromRow derive 제거 - PostgreSQL BIGINT는 signed이므로 수동으로 i64->u64 변환 필요
#[derive(Debug, Serialize, Deserialize, ToSchema)]
#[schema(as = Transaction)]
pub struct Transaction {
    /// Transaction ID (BIGSERIAL, auto-generated)
    /// 트랜잭션 ID (DB에서 자동 생성, 음수 불가능)
    pub id: u64,

    /// Input token mint address
    pub input_mint: String,

    /// Output token mint address
    pub output_mint: String,

    /// Input amount (음수 불가능)
    pub amount: u64,

    /// Expected output amount (음수 불가능)
    pub expected_out_amount: Option<u64>,

    /// User public key
    pub user_public_key: String,

    /// Transaction bytes (base58 encoded)
    pub transaction_bytes: String,

    /// Quote response (JSON)
    pub quote_response: Option<serde_json::Value>,

    /// Transaction status (created, sent, failed, etc.)
    pub status: String,

    /// Created timestamp
    pub created_at: DateTime<Utc>,
}

// ... 기존 TransactionStatus enum 그대로 ...
// Transaction 상태 enum (DB 저장용)
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TransactionStatus {
    Created,    // 트랜잭션 생성됨
    Sent,       // 네트워크에 전송됨
    Confirmed,  // 확인됨
    Failed,     // 실패함
}

impl TransactionStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            TransactionStatus::Created => "created",
            TransactionStatus::Sent => "sent",
            TransactionStatus::Confirmed => "confirmed",
            TransactionStatus::Failed => "failed",
        }
    }
}